[theme]
primaryColor = "#4B8BBE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableXsrfProtection = true
headless = true

[client]
showSidebarNavigation = true

[browser]
gatherUsageStats = false

[ui]
pageTitle = "Money Matters Studio"
favicon = "images/favicon.ico"
